//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonObject_Has_User
    {
        public int UserId { get; set; }
        public int LessonObjectId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual LessonObject LessonObject { get; set; }
        public virtual User User { get; set; }
    }
}
