//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TableCollegeEntities : DbContext
    {
        public TableCollegeEntities()
            : base("name=TableCollegeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<DayType> DayType { get; set; }
        public virtual DbSet<LessonObject> LessonObject { get; set; }
        public virtual DbSet<LessonObject_Has_User> LessonObject_Has_User { get; set; }
        public virtual DbSet<LessonsAtDay> LessonsAtDay { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Puplis> Puplis { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WeekType> WeekType { get; set; }
    }
}
